# Config format schema number
format_version: 2

###################
## Model options
model:
  name: "rangemambac"
  pretrained_component: "full"
  params:
    input_dim: 5
    stem_dim: 96

    stage_dims: [128, 192, 256]
    stage_depths: [3, 4, 6]

    patch_kernel: 7
    patch_stride: 4
    patch_padding: 3

    row_pad: [16, 8, 4]
    mamba:
      d_state: 16
      d_conv: 4
      expand: 2

    ffn_expand: 2
    dropout: 0.0
    force_mamba_fp32: true
    layer_scale_init: 1.0e-3
    use_boundary_head: false

loss:
  terms:
    - name: "cross_entropy"
      weight: 1.0
    - name: "boundary"
      weight: 1.0
    - name: "lovasz"
      weight: 1.5

postprocess:
  name: "knn"
  enabled: True
  params:
    knn: 7
    search: 7
    sigma: 1.0
    cutoff: 1.0

mlflow:
  enable: true
  tracking_uri: "http://140.245.117.232:5000"
  experiment_name: "rangeret"
  run_name: "[train] rangemambac_semantickitti"
  nested: false
  log_checkpoints: true
  log_code_snapshot: true

###################
## Dataset options
dataset:
  pc_dataset_type: "SemanticKITTI"
  collate_type: "collate_fn_default"
  ignore_label: 0
  data_config: "./config/labels/semantic-kitti.yaml"
  num_classes: 20
  max_points: 150000
  sensor:
    name: "HDL64"
    type: "spherical"
    fov_up: 3
    fov_down: -25
    img_prop:
      width: 1024
      height: 64
    img_means:
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds:
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16

###################
## Train params
train:
  epochs: 64
  learning_rate: 1.0e-3
  weight_decay: 0.05
  optimizer: AdamW
  batch_size: 8
  workers: 4
  epsilon_w: 0.001
  range_aug: True
  grad_clip: 1.0

  scheduler:
    name: "WarmupCosine"
    max_lr: 0.001
    total_steps: 1000
    pct_start: 0.02

  report_epoch: 1
  show_scans: False

